# Generated by Django 3.0.8 on 2020-08-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='longurl',
            field=models.TextField(),
        ),
    ]
